export type Product = {id:string;name:string;category:string;subcategory:string;description:string;image:string;images:string[];affiliate:string};
export const products: Product[] = [
{id:"n1",name:"Compact Wireless Earbuds",category:"Audio",subcategory:"Headphones & Earbuds",description:"A compact everyday wireless audio option with a clean, minimal design.",image:"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n2",name:"Minimal Desk Lamp",category:"Home & Kitchen",subcategory:"Lighting",description:"A modern desk light for workspaces, study corners and bedside tables.",image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n3",name:"Everyday Travel Backpack",category:"Travel",subcategory:"Bags & Luggage",description:"A practical backpack concept for daily commuting and short trips.",image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n4",name:"Smart Home Hub",category:"Electronics",subcategory:"Smart Home",description:"A compact smart-home control device designed for connected spaces.",image:"https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n5",name:"Mechanical Gaming Keyboard",category:"Gaming",subcategory:"PC Gaming",description:"A clean mechanical keyboard style for gaming and desktop setups.",image:"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n6",name:"Portable Coffee Maker",category:"Home & Kitchen",subcategory:"Kitchen Appliances",description:"A compact coffee-making option for home, office or travel use.",image:"https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n7",name:"Fitness Resistance Bands",category:"Sports & Fitness",subcategory:"Fitness Equipment",description:"A simple portable training accessory for home and travel workouts.",image:"https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"},
{id:"n8",name:"Classic Analog Watch",category:"Jewelry & Accessories",subcategory:"Watches",description:"A clean everyday watch design with a timeless appearance.",image:"https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80",images:["https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80"],affiliate:"https://www.aliexpress.com/"}
];
export const categories = [
["Electronics","Smart Home","Mobile Accessories","Gadgets"],["Computers & Accessories","Keyboards","Mice","Laptop Accessories"],["Audio","Headphones & Earbuds","Speakers","Microphones"],["Cameras","Action Cameras","Camera Accessories"],["Fashion","Men","Women","Accessories"],["Shoes","Sneakers","Casual Shoes","Sports Shoes"],["Beauty","Skincare","Hair Care","Beauty Tools"],["Home & Kitchen","Kitchen Appliances","Lighting","Storage"],["Furniture & Decor","Home Decor","Office Furniture"],["Sports & Fitness","Fitness Equipment","Outdoor Sports"],["Gaming","PC Gaming","Console Accessories"],["Books","Education","Lifestyle"],["Toys & Kids","Learning Toys","Games"],["Automotive","Car Accessories","Tools"],["Pet Supplies","Pet Accessories","Pet Care"],["Garden & Outdoor","Garden Tools","Outdoor Living"],["Travel","Bags & Luggage","Travel Accessories"],["Jewelry & Accessories","Watches","Fashion Jewelry"],["Tools & DIY","Hand Tools","DIY Accessories"],["Gifts & More","Gift Ideas","Seasonal Gifts"]
];
