backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: products
    label: Products
    folder: content/products
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Product Name, name: title, widget: string}
      - {label: Main Image, name: image, widget: image}
      - {label: Category, name: category, widget: string}
      - {label: Subcategory, name: subcategory, widget: string}
      - {label: Short Description, name: description, widget: text}
      - {label: Affiliate Link, name: affiliate, widget: string}
